### ISSUE TITLE
为什么windows用着可以，mac都安装不上呢？

### ISSUE THREAD

**Issue by guangfengzhuanhui** [kwp-lab/picgo-plugin-vikadata#1]
显示已安装，但是实际并没安装成功，没出现编辑按钮。

**Comment by kwp-lab** [comment]
![image](https://user-images.githubusercontent.com/35914355/181178161-95aee507-1032-47e1-9c4f-55ee2dc2caed.png)

打开 Picgo 的日志，粘贴到这里，我看一看。
我这边的 Mac 是可以正常使用此插件的

**Comment by kwp-lab** [comment]
应该已经修复此问题，请升级本插件至1.0.2版本
