### ISSUE TITLE
Mac arm架构 电脑上传vika失败

### ISSUE THREAD

**Issue by finachen** [kwp-lab/picgo-plugin-vikadata#3]
麻烦帮忙看看，最新mac air  m2芯片

<img width="1456" alt="CleanShot 2022-10-26 at 09 49 18@2x" src="https://user-images.githubusercontent.com/43667377/197915639-3d68c174-9e63-4b07-822a-d63f90230f8d.png">

**Comment by kwp-lab** [comment]
你好，应该是因为picgo-core 的版本升级导致此插件不兼容，已修复。

解决办法：
请在picgo软件里升级此插件至v1.0.2版本
